# io config
entsoe_token:
google_api_key:
opsd_vres_base_year: 2016


#matching config
matching_sources:
    - CARMA
    - GEO
    - GPD

# fully_included_sources:
#     - GPD

parallel_duke_processes: false
process_limit: 2
remove_missing_coords: true

#already build data
# matched_data_url: https://raw.githubusercontent.com/FRESNA/powerplantmatching/v0.4.8/powerplants.csv

#data config
GPD:
  reliability_score: 3
  fn: global_power_plant_database.csv
  #if outdated, look at http://datasets.wri.org/dataset/globalpowerplantdatabase
  url: http://datasets.wri.org/dataset/540dcf46-f287-47ac-985d-269b04bea4c6/resource/c240ed2e-1190-4d7e-b1da-c66b72e08858/download/globalpowerplantdatabasev120


display_net_caps: true
target_columns:
    - Name
    - Fueltype
    - Technology
    - Set
    - Country
    - Capacity
    - Efficiency
    - Duration
    - Volume_Mm3
    - DamHeight_m
    - StorageCapacity_MWh
    - DateIn
    - DateRetrofit
    - DateMothball
    - DateOut
    - lat
    - lon
    # - File
    - EIC
    - projectID
target_countries:
    - Marocco
    - Algeria
    - Tunisia
    - Libya
    - Egypt
target_fueltypes:
    - Bioenergy
    - Geothermal
    - Hard Coal
    - Hydro
    - Lignite
    - Natural Gas
    - Nuclear
    - Oil
    - Other
    - Solar
    - Waste
    - Wind
target_sets:
    - CHP
    - PP
    - Store
target_technologies:
    - CCGT
    - OCGT
    - Steam Turbine
    - Combustion Engine
    - Run-Of-River
    - Pumped Storage
    - Reservoir
    - Marine
    - Onshore
    - Offshore
    - PV
    - CSP

# heuristic config
fuel_to_lifetime:
    Bioenergy: 20
    Geothermal: 15
    Hard Coal: 45
    Hydro: 100
    Lignite: 45
    Natural Gas: 40
    Nuclear: 50
    Oil: 40
    Other: 5
    Solar: 25
    Waste: 25
    Wind: 25

# plotting config
fuel_to_color:
    OCGT: darkorange
    Hydro: seagreen
    Pumped hydro: limegreen
    Run-of-river: navy
    Ror: navy
    Lignite: saddlebrown
    Nuclear: yellow
    Solar: gold
    Windoff: cornflowerblue
    Windon: darkblue
    Offshore: cornflowerblue
    Onshore: darkblue
    Wind: steelblue
    Bioenergy: g
    Natural Gas: red
    CCGT: red
    Coal: k
    Hard Coal: dimgray
    Oil: darkgreen
    Other: silver
    Waste: grey
    Geothermal: orange
    Battery: purple
    Hydrogen Storage: teal
    Electro-mechanical: teal
    Total: gold
